services:
  ros:
    image: osrf/ros:noetic-desktop-full
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/src
    working_dir: /src
    tty: true
    command: bash
