services:
  ros:
    build:
      context: .
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ws:/ws
    working_dir: /ws
    tty: true
    command: bash
